package Appointments;

/**
* Appointments/HospInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointments.idl
* Saturday, 19 February, 2022 12:55:54 PM EST
*/

public final class HospInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Appointments.HospInterface value = null;

  public HospInterfaceHolder ()
  {
  }

  public HospInterfaceHolder (Appointments.HospInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Appointments.HospInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Appointments.HospInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Appointments.HospInterfaceHelper.type ();
  }

}
