package Appointments;


/**
* Appointments/HospInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointments.idl
* Saturday, 19 February, 2022 12:55:54 PM EST
*/

public interface HospInterfaceOperations 
{
  String addAppoint (String id, String appointId, String appointType, String capacity);
  String removeAppoint (String id, String appointId, String appointType);
  String listAppointAvailability (String id, String appointType);
  String bookAppoint (String id, String appointId, String appointType);
  String cancelAppoint (String id, String appointId, String appointType);
  String getBookingSchedule (String id);
  String swapAppoint (String id, String newAppointId, String newAppointType, String oldAppointId, String oldAppointType);
} // interface HospInterfaceOperations
