package Appointments;


/**
* Appointments/HospInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointments.idl
* Saturday, 19 February, 2022 12:55:54 PM EST
*/

public interface HospInterface extends HospInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HospInterface
